### ISSUE TITLE
Pre-CRAN Comments

### ISSUE THREAD

**Issue by BradyAJohnston** [JacobIMarsh/crosshap#1]
Some more comments about before you try and send it off to CRAN (which aren't checked for) but you will have it rejected on. 

- [x] DESCRIPTION file needs info instead of boilerplate description. Include a fair bit of detail here, the CRAN reviewers will look at it. Maybe include a paper reference or two when talking about what kind of data analysis it does.
- [x] dependencies: it looks like there are a few dependencies which can be removed from the description file, like `grid` and `scales` which are already dependencies of `ggplot2` so don't need to be explicitly stated. You can remove them and the check still passes
- [x] packages like `plyr` which are only used a single time from what I can tell. You probably want to just do that with base to remove the need for a whole package dependency

**Comment by jacobimarsh** [comment]
Thanks Brady!

For dependencies, I could remove `grid` and `stats` just from DESCRIPTION as they're present in base, but scales caused a lot of problems, I couldn't call it through `ggplot2` - tried a bunch of fixes but couldn't get it to work without keeping the scales:: prefix and dependency. 
Going through the others I removed `stringr`, `plyr`, `ggraph` in favour for base or already imported packages. 
There were other dependencies I only used a couple times like `ggpp`, but I left them in because I couldn't find alternatives that are as good, hopefully 16 dependencies isn't too many.  I'll work towards shipping to CRAN next week!

**Comment by BradyAJohnston** [comment]
All looks pretty good! It's not so much the deeper dependencies, but trying to get the primary dependencies down is always a good thing. If it gets really high then CRAN can sometimes comment about it. 

Now, do you have some tests in place to ensure that you didn't break anything by changing those functions to base functions  🥲

**Comment by jacobimarsh** [comment]
Tests added! I missed about 9% coverage of code comprising a deprecated function and a few basic helper scripts that would require downloading external data to test.

**Comment by jacobimarsh** [comment]
@BradyAJohnston I'm working on changing some of the core functions to return local instead of global variables which CRAN requested before publishing, I won't be in this afternoon but will resubmit in the next few days once all the tests and checks pass again

**Comment by BradyAJohnston** [comment]
No worries! Let me know if you have any specific questions
